name: CI

# Controls when the workflow will run
on: [tags]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run jlink
        run: jlink --output ${{ matrix.os }}/ --add-modules java.base,java.logging,java.naming,java.xml,java.sql,java.transaction.xa,java.security.sasl,java.desktop,java.management
      - name: Zip artifact on linux/macos
        if: ${{ matrix.os != 'windows-latest' }}
        run: zip -r ${{ matrix.os }}-jre.zip ${{ matrix.os }}

      - name: Zip artifact on win
        if: ${{ matrix.os == 'windows-latest' }}
        run: 7z a -tzip ${{ matrix.os }}-jre.zip ${{ matrix.os }}\

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to s3
        run: aws s3 cp ${{ matrix.os }}-jre.zip s3://yet-public/runtimes/${{ github.ref }}/${{ matrix.os }}-jre.zip
