name: Release Version

# Release on tagged versions
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    uses: yetanalytics/runtimer/.github/workflows/runtimer.yml@cf8c77d465f08962cd7901005b8cf197a6149ac1
  draft_release:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download ubuntu-latest Artifact
        uses: actions/download-artifact@v2
        with:
          name: ubuntu-20.04-jre

      - name: Download macOS-latest Artifact
        uses: actions/download-artifact@v2
        with:
          name: macos-10.15-jre

      - name: Download windows-latest Artifact
        uses: actions/download-artifact@v2
        with:
          name: windows-2019-jre

      - name: Craft Draft Release
        uses: softprops/action-gh-release@v1
        with:
          # Defaults:
          # name: [tag name]
          # tag_name: github.ref
          body: "## Release Notes\nTODO: Create great release notes!"
          draft: true
          files: '*-jre.zip'
