name: CI

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run jlink
        run: jlink --output ${{ matrix.os }}/ --add-modules java.base,java.logging,java.naming,java.xml,java.sql,java.transaction.xa,java.security.sasl,java.management

      - name: Zip artifact on linux/macos
        if: ${{ matrix.os != 'windows-latest' }}
        run: zip -r ${{ matrix.os }}-jre.zip ${{ matrix.os }}

      - name: Zip artifact on win
        if: ${{ matrix.os == 'windows-latest' }}
        run: 7z a -tzip ${{ matrix.os }}-jre.zip ${{ matrix.os }}\

      - name: Archive for transfer to draft_release job
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-jre
          path: ${{ matrix.os }}-jre.zip

  draft_release:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download ubuntu-latest Artifact
        uses: actions/download-artifact@v2
        with:
          name: ubuntu-latest-jre

      - name: Download macOS-latest Artifact
        uses: actions/download-artifact@v2
        with:
          name: macOS-latest-jre

      - name: Download windows-latest Artifact
        uses: actions/download-artifact@v2
        with:
          name: windows-latest-jre

      - name: Craft Draft Release
        uses: softprops/action-gh-release@v1
        with:
          # Defaults:
          # name: [tag name]
          # tag_name: github.ref
          body: "## Release Notes\nTODO: Create great release notes!"
          draft: true
          files: *-latest-jre.zip
